### ISSUE TITLE
Changing JSON Path

### ISSUE THREAD

**Issue by Tresmos** [gclem/overwatch-webapi#1]
I want to get player's competitive lost count but its JSON path is changing sometimes.

Sometimes its "competitive.global.games_lost", 
sometimes "competitive.global.{count,_plural,_one_{game}_other_{games}}_lost".

I'm hosting it myself but its same with your self hosted one.It looks like its random.

**Comment by gclem** [comment]
Do you have some username to test ? 
Or is it totally random ?

Seems it's a templating problem when the page is loaded. 
As I scrap the page, seems that the page isn't templated when getting it.

**Comment by Tresmos** [comment]
Here some btags that i used

cRashTr-21408
Zola-21326
Tresmos-2135

**Comment by gclem** [comment]
Seems to come from Overwatch web server. 

I'll close this, feel free to keep up updated.

**Comment by Tresmos** [comment]
yeah its still happening sometimes.If its because of overwatch web server
rip :/
